import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { startServer } from '../src/server.mjs';
import { loadConfig } from '../src/config.mjs';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { appRecovery } from '../src/agent-data.mjs';
import { indexedDB } from 'fake-indexeddb';
let app,upstream,root,url,upstreamUrl,owner,other,remoteOwner,client,device;
const getValue=r=>JSON.parse(r.content[0].text);
async function req(base,route,token,body,method,signal){const r=await fetch(base+route,{method:method||(body?'POST':'GET'),headers:{...(token?{authorization:'Bearer '+token}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal});return {status:r.status,value:await r.json()};}
const api=(route,body,method,signal)=>req(url,'/v1/agent'+route,owner.session.token,body,method,signal);
async function sdk(scopes){const grant=(await api('/tokens',{label:'test-write',scopes})).value,c=new Client({name:'write-test',version:'1'});await c.connect(new StreamableHTTPClientTransport(new URL(url+'/mcp'),{requestInit:{headers:{authorization:'Bearer '+grant.token}}}));return c;}
const workout=(weight=60,reps=8)=>({name:'胸部训练',date:'2026-10-09T04:00:00.000Z',note:'今天睡眠一般',durationSeconds:1600,exercises:[{exerciseId:'bench_press',restSeconds:120,note:'肩胛收紧',sets:[{weight,reps,restSeconds:120,completed:true,note:'最后一组很吃力',state:'动作稳定',feeling:'右侧略疲劳',additionalNotes:'下次先热身',rpe:8,rir:2}]}]});
const meal={recordedAt:'2026-10-09T04:00:00.000Z',mealType:'午餐',foodName:'PHOTO_ESTIMATE_PRIVATE',amount:'一盘',calories:520,proteinGrams:30,carbsGrams:50,fatGrams:20,estimated:true,note:'份量估计，油量不确定'};
test.before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'traintool-writes-'));const config=(name,extra={})=>loadConfig({NODE_ENV:'test',KILO_DATA_DIR:path.join(root,name),KILO_DATABASE_PATH:path.join(root,name,'db.sqlite'),KILO_MEDIA_DIR:path.join(root,name,'media'),KILO_ENABLE_TEST_MEMBER:'true',KILO_ENABLE_PASSWORD_REGISTRATION:'true',...extra});upstream=await startServer({port:0,config:config('upstream')});upstreamUrl='http://127.0.0.1:'+upstream.address().port;app=await startServer({port:0,config:config('web',{KILO_AGENT_BACKEND_URL:upstreamUrl})});url='http://127.0.0.1:'+app.address().port;owner=(await req(url,'/v1/auth/phone/login',null,{identifier:'123',password:'123'})).value;other=(await req(url,'/v1/auth/register',null,{identifier:'other-write-member',password:'pass1234'})).value;app.context.db.prepare("UPDATE entitlements SET membership='forever' WHERE user_id=?").run(other.user.id);remoteOwner=(await req(upstreamUrl,'/v1/auth/phone/login',null,{identifier:'123',password:'123'})).value;client=await sdk(['workouts','workouts.write','nutrition','nutrition.write','profile','profile.write']);const local=new Map();globalThis.localStorage={getItem:k=>local.get(k),setItem:(k,v)=>local.set(k,v)};globalThis.indexedDB=indexedDB;device=await import('../agent-web/device-storage.js');});
test.after(async()=>{app.context.browserBroker?.close();device.closeDeviceDatabase();await client.close();await app.closeGracefully();await upstream.closeGracefully();await fs.rm(root,{recursive:true,force:true});});
test('Writable MCP lists explicit write tools and App catalogue with real media',async()=>{const names=(await client.listTools()).tools.map(t=>t.name);for(const name of ['save_workout','save_training_plan','save_active_workout','save_nutrition_entry','save_body_profile','save_body_weight','save_nutrition_goal','get_app_exercise','read_exercise_progress'])assert.ok(names.includes(name));const library=getValue(await client.callTool({name:'search_app_exercises',arguments:{query:'卧推'}}));assert.ok(library.records.some(e=>e.id==='bench_press'));assert.ok(library.records.some(e=>e.imageAsset&&e.steps?.length));const jpg=library.records.find(e=>e.imageAsset).imageAsset;assert.equal((await fetch(url+'/agent/exercise-media/'+jpg)).status,200);});
test('MCP training persists App-compatible per-set notes and deduplicates retries',async()=>{const args={idempotencyKey:'workout-once-123',record:workout()};const a=getValue(await client.callTool({name:'save_workout',arguments:args}));const b=getValue(await client.callTool({name:'save_workout',arguments:args}));assert.equal(b.replayed,true);assert.equal(a.recordId,b.recordId);const record=a.record;assert.equal(record.volume,480);assert.equal(record.effectiveSets,1);assert.equal(record.exercises[0].sets[0].restSeconds,120);for(const fragment of ['最后一组很吃力','动作稳定','右侧略疲劳','下次先热身'])assert.ok(record.exercises[0].sets[0].note.includes(fragment));assert.equal(record.exercises[0].note,'肩胛收紧');assert.equal(record.note,'今天睡眠一般');const row=app.context.db.prepare("SELECT payload_json FROM sync_entities WHERE user_id=? AND entity_type='workout'").get(owner.user.id);assert.equal(JSON.parse(row.payload_json).id,a.recordId);assert.equal((await client.callTool({name:'save_workout',arguments:{...args,record:workout(65)}})).isError,true);});
async function verifyAppend(c,prefix){
 const plan=getValue(await c.callTool({name:'save_training_plan',arguments:{idempotencyKey:prefix+'-create-plan',record:{name:'追加测试计划',note:'原计划备注',exercises:workout().exercises}}}));
 const args={idempotencyKey:prefix+'-append-once',planId:plan.recordId,expectedVersion:plan.record.updatedAt,exercise:{exerciseId:'bench_press',note:'第二动作备注',sets:[{weight:25,reps:10,restSeconds:80,note:'追加组感受'}]}};
 const first=getValue(await c.callTool({name:'append_plan_exercise',arguments:args}));
 assert.equal(first.record.exercises.length,2);assert.equal(first.record.note,'原计划备注');
 assert.equal(first.record.exercises[0].note,'肩胛收紧');
 assert.notEqual(first.record.exercises[0].id,first.record.exercises[1].id);
 assert.notEqual(first.record.exercises[0].sets[0].id,first.record.exercises[1].sets[0].id);
 const replay=getValue(await c.callTool({name:'append_plan_exercise',arguments:args}));
 assert.equal(replay.replayed,true);assert.equal(replay.record.exercises.length,2);
 const stale=await c.callTool({name:'append_plan_exercise',arguments:{...args,idempotencyKey:prefix+'-stale-append'}});assert.equal(stale.isError,true);
 await c.callTool({name:'save_active_workout',arguments:{idempotencyKey:prefix+'-create-active',record:workout()}});
 const activeArgs={idempotencyKey:prefix+'-append-active',exercise:args.exercise};
 const active=getValue(await c.callTool({name:'append_current_workout_exercise',arguments:activeArgs}));assert.equal(active.record.exercises.length,2);
 assert.equal(getValue(await c.callTool({name:'append_current_workout_exercise',arguments:activeArgs})).replayed,true);
 assert.equal(getValue(await c.callTool({name:'read_current_workout',arguments:{}})).workout.exercises.length,2);
}
test('Atomic append preserves original notes, uses unique set IDs, deduplicates retries and rejects stale versions',async()=>{await verifyAppend(client,'local');});
test('Exercise progress compares weight/reps by stable exercise and training date',async()=>{await client.callTool({name:'save_workout',arguments:{idempotencyKey:'workout-next-123',record:{...workout(65,9),date:'2026-10-10T04:00:00.000Z'}}});const data=getValue(await client.callTool({name:'read_exercise_progress',arguments:{exerciseId:'bench_press'}}));assert.equal(data.sessions.length,2);assert.deepEqual(data.sessions.map(s=>s.maxWeight),[60,65]);assert.deepEqual(data.sessions.map(s=>s.maxReps),[8,9]);assert.ok(data.sessions[0].sets[0].note.includes('右侧略疲劳'));const web=(await api('/exercise-progress?exerciseId=bench_press')).value;assert.deepEqual(web.sessions,data.sessions);});
test('Calories and AI-calculated target persist; deleting a meal preserves the rest of backup',async()=>{const goal=await client.callTool({name:'save_nutrition_goal',arguments:{idempotencyKey:'goal-20261009',record:{date:'2026-10-09',calories:2300,goalType:'减脂',basis:'由外部 AI 根据资料估算，用户确认',source:'external-ai'}}});assert.ok(!goal.isError);const saved=getValue(await client.callTool({name:'save_nutrition_entry',arguments:{idempotencyKey:'photo-meal-123',record:meal}}));let summary=getValue(await client.callTool({name:'read_nutrition_day',arguments:{date:'2026-10-09'}}));assert.equal(summary.intake.calories,520);assert.equal(summary.remainingCalories,1780);assert.ok(summary.records[0].recognitionWarnings.length);const removed=await client.callTool({name:'save_nutrition_entry',arguments:{idempotencyKey:'delete-meal-123',action:'delete',recordId:saved.recordId}});assert.ok(!removed.isError);summary=getValue(await client.callTool({name:'read_nutrition_day',arguments:{date:'2026-10-09'}}));assert.equal(summary.intake.calories,0);assert.equal(summary.goal.calories,2300);assert.equal(app.context.db.prepare("SELECT deleted_at FROM sync_entities WHERE user_id=? AND entity_id='mobile_backup_v1'").get(owner.user.id).deleted_at,null);});
test('Read-only tokens and other accounts cannot mutate or read private records',async()=>{const reader=await sdk(['workouts']);try{assert.ok(!(await reader.listTools()).tools.some(t=>t.name==='save_workout'));assert.equal((await reader.callTool({name:'save_workout',arguments:{idempotencyKey:'denied-test',record:workout()}})).isError,true);}finally{await reader.close();}const isolated=(await req(url,'/v1/agent/bootstrap',other.session.token)).value;assert.equal(isolated.workouts.length,0);const foreign=(await req(url,'/v1/agent/records/workout',other.session.token,{idempotencyKey:'foreign-record',action:'delete',recordId:(await api('/bootstrap')).value.workouts[0].id}));assert.equal(foreign.status,404);});
test('Remote writes reach actual App sync API, preserve unrelated fields and recover lost response',async()=>{await req(upstreamUrl,'/v1/sync',remoteOwner.session.token,{entityType:'settings',entityId:'mobile_backup_v1',baseRevision:0,payload:{schemaVersion:1,unknownPreserved:{important:true},trainingProfile:{completed:true,profile:{heightCm:181}},nutrition:[]}});await api('/backend',{identifier:'123',password:'123'});const c=await sdk(['nutrition','nutrition.write','profile','profile.write','workouts','workouts.write']);try{await verifyAppend(c,'remote');const args={idempotencyKey:'remote-photo-once',record:meal};const saved=getValue(await c.callTool({name:'save_nutrition_entry',arguments:args}));let remote=(await req(upstreamUrl,'/v1/sync?entityType=settings',remoteOwner.session.token)).value.entities[0];assert.equal(remote.payload.nutrition[0].foodName,meal.foodName);assert.equal(remote.payload.unknownPreserved.important,true);app.context.db.prepare('UPDATE web_mutations SET result_json=NULL WHERE user_id=? AND binding=?').run(owner.user.id,remoteOwner.user.id);const retry=getValue(await c.callTool({name:'save_nutrition_entry',arguments:args}));assert.equal(retry.replayed,true);assert.equal(retry.recordId,saved.recordId);const record=getValue(await c.callTool({name:'save_workout',arguments:{idempotencyKey:'remote-workout-123',record:workout(70,7)}}));remote=(await req(upstreamUrl,'/v1/sync?entityType=workout',remoteOwner.session.token)).value.entities.find(e=>e.entityId===record.recordId);assert.ok(remote.payload.exercises[0].sets[0].note.includes('下次先热身'));await c.callTool({name:'save_body_profile',arguments:{idempotencyKey:'remote-profile-123',record:{weightKg:79}}});const profile=getValue(await c.callTool({name:'read_body_profile',arguments:{}}));assert.equal(profile.profile.heightCm,181);assert.equal(profile.profile.weightKg,79);}finally{await c.close();}});
test('Browser mode relay uses actual IndexedDB transactions, keeps records out of server and survives reopen',async()=>{await api('/storage',{mode:'browser',deviceId:device.deviceId});const stop=device.startDeviceBridge(owner.user.id,async(route,body,method,signal)=>{const result=await api(route,body,method,signal);if(result.status!==200)throw new Error(result.value.error);return result.value;});try{for(let i=0;i<25;i++){if((await api('/storage')).value.online)break;await new Promise(r=>setTimeout(r,10));}const c=await sdk(['workouts','workouts.write','nutrition','nutrition.write']);try{await verifyAppend(c,'browser');const args={idempotencyKey:'device-food-123',record:{...meal,foodName:'DEVICE_ONLY_PRIVATE_FOOD'}};const saved=getValue(await c.callTool({name:'save_nutrition_entry',arguments:args}));assert.equal(saved.destination,'user-browser');const replay=getValue(await c.callTool({name:'save_nutrition_entry',arguments:args}));assert.equal(replay.replayed,true);assert.ok(!JSON.stringify(app.context.db.prepare('SELECT * FROM sync_entities').all()).includes('DEVICE_ONLY_PRIVATE_FOOD'));assert.ok(!JSON.stringify(app.context.db.prepare('SELECT * FROM web_mutations').all()).includes('DEVICE_ONLY_PRIVATE_FOOD'));assert.equal((await api('/bootstrap')).value.nutrition[0].foodName,'DEVICE_ONLY_PRIVATE_FOOD');device.closeDeviceDatabase();const reopened=await device.executeDeviceOperation(owner.user.id,{type:'read'});assert.equal(reopened.nutrition[0].foodName,'DEVICE_ONLY_PRIVATE_FOOD');const isolated=await device.executeDeviceOperation(other.user.id,{type:'read'});assert.equal(isolated.nutrition.length,0);const w=getValue(await c.callTool({name:'save_workout',arguments:{idempotencyKey:'device-training-123',record:workout(45,12)}}));assert.ok(w.record.exercises[0].sets[0].note.includes('右侧略疲劳'));const progress=getValue(await c.callTool({name:'read_exercise_progress',arguments:{exerciseId:'bench_press'}}));assert.equal(progress.sessions[0].maxWeight,45);const active=getValue(await c.callTool({name:'save_active_workout',arguments:{idempotencyKey:'device-current-123',record:workout(30,10)}}));assert.equal(active.recordId,'active-workout');assert.equal(getValue(await c.callTool({name:'read_current_workout',arguments:{}})).workout.name,'胸部训练');}finally{await c.close();}}finally{stop();app.context.browserBroker.cancel(owner.user.id);}});
test('Offline browser and mismatched device return explicit errors; mode switch revokes grants',async()=>{const before=await sdk(['nutrition']);try{const result=await before.callTool({name:'read_nutrition_day',arguments:{date:'2026-10-09'}});assert.equal(result.isError,true);assert.ok(result.content[0].text.includes('browser_device_offline'));const wrong=await api('/device/poll?deviceId=00000000-0000-0000-0000-000000000000');assert.equal(wrong.status,403);await api('/storage',{mode:'server'});await assert.rejects(before.callTool({name:'read_nutrition_day',arguments:{date:'2026-10-09'}}));const persisted=await device.executeDeviceOperation(owner.user.id,{type:'read'});assert.equal(persisted.nutrition.length,1);}finally{await before.close();}});
test('Recovery mirrors App effort and 38-hour exponential fatigue with secondary contribution',()=>{const at=new Date('2026-10-10T04:00:00Z');const result=appRecovery({workouts:[{id:'a',...workout()}]},at);const chest=result.find(m=>m.id==='chest');const effort=1.25-2*.09;assert.equal(chest.recoveryPercent,Math.round(100-effort*Math.exp(-24/38)*9.2));assert.equal(chest.trainingCount,1);assert.equal(chest.hoursSinceLast,24);assert.equal(result.find(m=>m.id==='hamstring').recoveryPercent,100);});
