import { randomUUID } from 'node:crypto';
const fail=(status,code)=>{throw Object.assign(new Error(code),{status,code});};
export function initializeBrowserStorage(db){db.exec(`CREATE TABLE IF NOT EXISTS web_storage(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,mode TEXT NOT NULL DEFAULT 'server',device_id TEXT,updated_at TEXT NOT NULL);`);}
export function storageStatus(ctx,userId){const row=ctx.db.prepare('SELECT * FROM web_storage WHERE user_id=?').get(userId);return {mode:row?.mode||'server',deviceId:row?.device_id||null,online:!!ctx.browserBroker?.online(userId,row?.device_id),userId,mcpUrl:ctx.cfg.publicBaseUrl+'/mcp',localNotice:'本地记录保存在绑定浏览器的 IndexedDB。网站中转请求及结果，但不持久化记录。浏览器需要保持在线。'};}
export function selectStorage(ctx,userId,body){if(!['browser','server'].includes(body.mode))fail(400,'invalid_storage_mode');if(body.mode==='browser'&&!/^[a-f0-9-]{36}$/.test(body.deviceId||''))fail(400,'device_id_required');ctx.browserBroker?.cancel(userId);ctx.db.transaction(()=>{ctx.db.prepare('INSERT INTO web_storage VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET mode=excluded.mode,device_id=excluded.device_id,updated_at=excluded.updated_at').run(userId,body.mode,body.mode==='browser'?body.deviceId:null,new Date().toISOString());ctx.db.prepare('UPDATE agent_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').run(new Date().toISOString(),userId);})();return storageStatus(ctx,userId);}
export class BrowserBroker {
 constructor(timeout=25000){this.timeout=timeout;this.jobs=new Map();this.heartbeats=new Map();this.waiters=new Map();}
 key(user,device){return user+':'+device;}
 online(user,device){return device&&Date.now()-(this.heartbeats.get(this.key(user,device))||0)<22000;}
 async request(user,device,operation){if(!this.online(user,device))fail(503,'browser_device_offline');if([...this.jobs.values()].filter(j=>j.user===user).length>=8||this.jobs.size>=200)fail(429,'browser_bridge_busy');return new Promise((resolve,reject)=>{const id=randomUUID(),job={id,user,device,operation,resolve,reject};job.timer=setTimeout(()=>{this.jobs.delete(id);reject(Object.assign(new Error('browser_device_offline'),{status:503,code:'browser_device_offline'}));},this.timeout);this.jobs.set(id,job);this.waiters.get(this.key(user,device))?.();});}
 async poll(user,device,signal){const key=this.key(user,device);this.heartbeats.set(key,Date.now());const pending=()=>[...this.jobs.values()].filter(j=>j.user===user&&j.device===device&&!j.delivered);if(!pending().length)await new Promise(resolve=>{const done=()=>{clearTimeout(timer);signal?.removeEventListener('abort',done);if(this.waiters.get(key)===done)this.waiters.delete(key);resolve();};const timer=setTimeout(done,15000);this.waiters.get(key)?.();this.waiters.set(key,done);signal?.addEventListener('abort',done,{once:true});});return pending().map(j=>{j.delivered=true;return {id:j.id,operation:j.operation};});}
 complete(user,device,id,result,error){const j=this.jobs.get(id);if(!j||j.user!==user||j.device!==device)fail(404,'bridge_request_not_found');clearTimeout(j.timer);this.jobs.delete(id);if(error)j.reject(Object.assign(new Error(error),{status:error.includes('conflict')||error.includes('reused')?409:400,code:String(error).slice(0,200)}));else j.resolve(result);}
 cancel(user){for(const j of this.jobs.values())if(j.user===user){clearTimeout(j.timer);this.jobs.delete(j.id);j.reject(Object.assign(new Error('storage_mode_changed'),{status:409,code:'storage_mode_changed'}));}for(const k of this.heartbeats.keys())if(k.startsWith(user+':'))this.heartbeats.delete(k);}
 close(){for(const j of this.jobs.values()){clearTimeout(j.timer);j.reject(Object.assign(new Error('bridge_closed'),{code:'bridge_closed'}));}this.jobs.clear();for(const wake of this.waiters.values())wake();this.waiters.clear();}
}
export function broker(ctx){return ctx.browserBroker??=new BrowserBroker();}
export async function browserRequest(ctx,userId,operation){const status=storageStatus(ctx,userId);if(status.mode!=='browser')fail(409,'storage_mode_changed');return broker(ctx).request(userId,status.deviceId,operation);}
export function isBrowserStorage(ctx,userId){return storageStatus(ctx,userId).mode==='browser';}
