/// Converts the English names from the public exercise dataset into compact
/// Chinese display names. The original English name is retained separately for
/// search and attribution.
String chineseExerciseName(
  String englishName, {
  required String equipment,
  required String muscle,
}) {
  var value = englishName.toLowerCase().trim();
  value = value
      .replaceAll(RegExp(r'\((male|female)\)'), '')
      .replaceAll(RegExp(r'\bv\.?\s*\d+\b'), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();

  const exact = <String, String>{
    '3/4 sit-up': '四分之三仰卧起坐',
    '45° side bend': '45°侧屈',
    'air bike': '空中自行车卷腹',
    'ankle circles': '踝关节绕环',
    'back and forth step': '前后踏步',
    'back lever': '后水平支撑',
    'balance board': '平衡板训练',
    'burpee': '波比跳',
    'dead bug': '死虫式',
    'good morning': '早安式',
    'high knee skips': '高抬腿跳',
    'inchworm': '毛毛虫爬行',
    'jumping jack': '开合跳',
    'mountain climber': '登山跑',
    'pike push up': '折刀俯卧撑',
    'russian twist': '俄罗斯转体',
    'scapula dips': '肩胛下沉',
    'sissy squat': '西西深蹲',
    'star jump': '星形跳',
    'superman': '超人式',
  };
  final direct = exact[value];
  if (direct != null) return direct;

  const phrases = <String, String>{
    'close grip': '窄握',
    'wide grip': '宽握',
    'neutral grip': '对握',
    'underhand grip': '反握',
    'overhand grip': '正握',
    'one arm': '单臂',
    'single arm': '单臂',
    'one leg': '单腿',
    'single leg': '单腿',
    'two arm': '双臂',
    'two legs': '双腿',
    'upper body': '上肢',
    'lower body': '下肢',
    'body weight': '自重',
    'stability ball': '健身球',
    'exercise ball': '健身球',
    'medicine ball': '药球',
    'bosu ball': '波速球',
    'ez barbell': '曲杆杠铃',
    'olympic barbell': '奥杆',
    'smith machine': '史密斯机',
    'leverage machine': '固定器械',
    'resistance band': '阻力带',
    'straight leg': '直腿',
    'bent over': '俯身',
    'bent-over': '俯身',
    'chest supported': '胸托',
    'chest-supported': '胸托',
    'behind the neck': '颈后',
    'over head': '过顶',
    'front raise': '前平举',
    'lateral raise': '侧平举',
    'rear delt': '后三角肌',
    'hip thrust': '臀推',
    'hip extension': '伸髋',
    'hip abduction': '髋外展',
    'hip adduction': '髋内收',
    'leg extension': '腿屈伸',
    'leg curl': '腿弯举',
    'calf raise': '提踵',
    'wrist curl': '腕弯举',
    'biceps curl': '肱二头肌弯举',
    'bicep curl': '肱二头肌弯举',
    'triceps extension': '肱三头肌伸展',
    'tricep extension': '肱三头肌伸展',
    'bench press': '卧推',
    'shoulder press': '肩推',
    'chest press': '推胸',
    'overhead press': '过顶推举',
    'military press': '军姿推举',
    'push up': '俯卧撑',
    'push-up': '俯卧撑',
    'pull up': '引体向上',
    'pull-up': '引体向上',
    'chin up': '反握引体向上',
    'chin-up': '反握引体向上',
    'lat pulldown': '高位下拉',
    'pull down': '下拉',
    'pulldown': '下拉',
    'face pull': '面拉',
    'upright row': '直立划船',
    'seated row': '坐姿划船',
    'bent arm': '屈臂',
    'stiff leg': '直腿',
    'romanian deadlift': '罗马尼亚硬拉',
    'sumo deadlift': '相扑硬拉',
    'split squat': '分腿蹲',
    'front squat': '前蹲',
    'hack squat': '哈克深蹲',
    'goblet squat': '高脚杯深蹲',
    'reverse fly': '反向飞鸟',
    'chest fly': '夹胸飞鸟',
    'pec deck': '蝴蝶机夹胸',
    'side bend': '侧屈',
    'sit up': '仰卧起坐',
    'sit-up': '仰卧起坐',
    'v up': 'V字卷腹',
    'v-up': 'V字卷腹',
    'leg raise': '举腿',
    'knee raise': '提膝',
    'toe touch': '触足卷腹',
    'heel touch': '触踵卷腹',
    'jump rope': '跳绳',
    'battle rope': '战绳',
  };
  for (final entry in phrases.entries) {
    value = value.replaceAll(entry.key, ' ${entry.value} ');
  }

  const words = <String, String>{
    'assisted': '辅助',
    'weighted': '负重',
    'bodyweight': '自重',
    'band': '弹力带',
    'barbell': '杠铃',
    'dumbbell': '哑铃',
    'cable': '绳索',
    'kettlebell': '壶铃',
    'lever': '固定器械',
    'machine': '器械',
    'smith': '史密斯机',
    'rope': '绳索',
    'sled': '雪橇',
    'roller': '滚轮',
    'wheel': '健腹轮',
    'hammer': '锤式',
    'bench': '训练凳',
    'floor': '地板',
    'wall': '靠墙',
    'standing': '站姿',
    'seated': '坐姿',
    'lying': '卧姿',
    'prone': '俯卧',
    'supine': '仰卧',
    'kneeling': '跪姿',
    'hanging': '悬垂',
    'incline': '上斜',
    'decline': '下斜',
    'vertical': '垂直',
    'horizontal': '水平',
    'alternate': '交替',
    'alternating': '交替',
    'reverse': '反向',
    'front': '前侧',
    'rear': '后侧',
    'side': '侧向',
    'lateral': '侧向',
    'overhead': '过顶',
    'low': '低位',
    'high': '高位',
    'wide': '宽距',
    'narrow': '窄距',
    'close': '窄距',
    'single': '单侧',
    'double': '双侧',
    'straight': '直臂',
    'bent': '屈曲',
    'rotation': '旋转',
    'internal': '内旋',
    'external': '外旋',
    'twist': '转体',
    'twisting': '转体',
    'curl': '弯举',
    'press': '推举',
    'pushdown': '下压',
    'pullover': '上拉',
    'row': '划船',
    'raise': '抬举',
    'extension': '伸展',
    'fly': '飞鸟',
    'squat': '深蹲',
    'lunge': '弓步',
    'deadlift': '硬拉',
    'crunch': '卷腹',
    'plank': '平板支撑',
    'dip': '双杠臂屈伸',
    'dips': '双杠臂屈伸',
    'shrug': '耸肩',
    'bridge': '臀桥',
    'stretch': '拉伸',
    'jump': '跳跃',
    'step': '踏步',
    'run': '跑',
    'walk': '行走',
    'clean': '翻举',
    'snatch': '抓举',
    'kickback': '后踢',
    'abduction': '外展',
    'adduction': '内收',
    'calves': '小腿',
    'calf': '小腿',
    'chest': '胸部',
    'shoulder': '肩部',
    'triceps': '肱三头肌',
    'tricep': '肱三头肌',
    'biceps': '肱二头肌',
    'bicep': '肱二头肌',
    'forearm': '前臂',
    'wrist': '手腕',
    'back': '背部',
    'lat': '背阔肌',
    'hip': '髋部',
    'glute': '臀肌',
    'glutes': '臀肌',
    'hamstring': '腘绳肌',
    'quadriceps': '股四头肌',
    'quads': '股四头肌',
    'leg': '腿部',
    'legs': '腿部',
    'knee': '膝部',
    'knees': '膝部',
    'ankle': '踝部',
    'arm': '手臂',
    'arms': '手臂',
    'neck': '颈部',
    'head': '头部',
    'full': '全程',
    'half': '半程',
    'concentration': '集中式',
    'preacher': '牧师凳',
    'russian': '俄罗斯',
    'pallof': '帕洛夫',
    'arnold': '阿诺德',
    'spider': '蜘蛛式',
    'jefferson': '杰弗森',
    'zercher': '泽奇式',
    'and': '',
    'with': '',
    'without': '无',
    'on': '',
    'to': '',
    'the': '',
    'of': '',
    'in': '',
    'from': '',
    'both': '双侧',
    'each': '每侧',
    'one': '单侧',
    'two': '双侧',
  };

  final pieces = value
      // Hyphenated variants such as `close-grip push-up` used to remain one
      // unknown token and were silently discarded. That collapsed distinct
      // exercises into the same Chinese name and made correct media look
      // mismatched. Treat separators as word boundaries before translating.
      .replaceAll('-', ' ')
      .replaceAll(RegExp(r'[^a-z0-9\u4e00-\u9fff°/.]+'), ' ')
      .split(' ')
      .where((part) => part.isNotEmpty)
      .map((part) {
        if (!RegExp(r'[a-z]').hasMatch(part)) return part;
        return words[part] ?? '';
      })
      .where((part) => part.isNotEmpty)
      .toList();
  final translated = pieces.join('·').replaceAll(RegExp(r'·+'), '·');
  if (translated.replaceAll(RegExp(r'[^\u4e00-\u9fff]'), '').length >= 2) {
    return translated;
  }
  return '$equipment$muscle训练';
}
